// angular/src/app/favorites/favorites.component.ts
import { Component } from '@angular/core';
import { GlobalVariables } from "../global-variables";
import { _Image } from "../types/Interfaces"

@Component({
  selector: 'app-favorites',
  templateUrl: './favorites.component.html',
  styleUrls: ['./favorites.component.css']
})
export class FavoritesComponent {
	favorites = GlobalVariables.favorites;

  removeFromFavorites(img : _Image) : void {
    GlobalVariables.favorites.splice(
      GlobalVariables.favorites.indexOf(img),1);
  }
}

<section *ngIf="favorites.length > 0; else NoResult" class="images" id="section-images">
	<div *ngFor="let img of favorites" class="img-container">
	  <img [src]="img.url" alt="" />
	  <i (click)="removeFromFavorites(img)" class="fas fa-star favs filled"></i>
	</div>
  </section>
  <ng-template #NoResult>
	<p>No favorites yet</p>
  </ng-template>

// react-js/src/pages/Favorites.js
import React from "react";
import "../App.css";

export default function Favorites(props) {
  let { favorites, removeFromFavorites } = props;
  const displayImages = () => {
    return favorites.map((img, i) => {
      let { url, id } = img;
      return (
        <div className="img-container" key={id}>
          <img src={url} key={i} alt="" />
          <div onClick={() => removeFromFavorites(url, id)}>
            <i className="fas fa-star favs filled" />
          </div>
        </div>
      );
    });
  };

  return (
    <section class="images" id="section-images">
      {favorites.length > 0 ? displayImages() : <p>No Favorites yet</p>}
    </section>
  );
}
