// vue3-composition-api/src/views/Home.vue
<template>
  <div class="home">
    <form id="form" @submit.prevent="handleSubmitForm">
      <label for="searchTerm">Search an image</label>
      <input
        v-model="searchTerm"
        class="u-full-width"
        type="text"
        id="searchTerm"
        name="searchTerm"
      />
      <button type="submit" class="center-el">Search</button>
    </form>
    <img v-if="loading" class="loader" src="../assets/loading.svg" alt="loading" />
    <section v-if="!loading && formSubmitted" class="images" id="section-images">
      <div v-if="images.length > 0">
        <div v-for="(img, i) in images" :key="i" class="img-container">
          <img :src="img.webformatURL" :alt="searchTerm" />
          <FavoritesIcon :img="img" />
        </div>
      </div>
      <div v-else>
        <p>No results found</p>
      </div>
    </section>
  </div>
</template>

<script>
import { ref } from "@vue/composition-api";
import FavoritesIcon from "../components/FavoritesIcon";

export default {
  name: "home",
  components: {
    FavoritesIcon
  },

  setup(_, context) {
    let searchTerm = ref(""),
      loading = ref(false),
      formSubmitted = ref(false),
      images = ref(context.root.$images);
      //no need to set up vuex for only 1 variable

    const toggleLoadingStatus = () => (loading.value = !loading.value);

    const getImages = async searchTerm => {
      try {
        //You can use this key or create your own.
        //If so , make sur to put it in a .env file if you don't want to share it.
        let res = await fetch(
          `https://pixabay.com/api/?key=16470380-d4d16b7e542ef904b93d0542c&q=${searchTerm}&image_type=photo&page=1`,
          {
            method: "GET",
            "Access-Control-Allow-Origin": "*"
          }
        );
        let processed = await res.json();
        return processed.hits;
      } catch (err) {
        alert(err.message);
      }
    };

    const handleSubmitForm = async () => {
      toggleLoadingStatus();
      formSubmitted.value = true;
      images.value = await getImages(searchTerm.value);
      toggleLoadingStatus();
    };

    return {
      searchTerm,
      handleSubmitForm,
      loading,
      formSubmitted,
      images
    };
  }
};
</script>

// react-js/src/pages/Home.js
import React, { useState } from "react";
import loader from "../loader.svg";
import "../App.css";

export default function Home(props) {
  const [loading, setLoading] = useState(false);
  const [images, setImages] = useState([]);
  const [requested, setRequested] = useState(false);
  let { favorites, addToFavorites, removeFromFavorites } = props;

  const getImages = async (searchTerm) => {
    try {
      setRequested(false);
      let res = await fetch(
        `https://pixabay.com/api/?key=16470380-d4d16b7e542ef904b93d0542c&q=${searchTerm}&image_type=photo&page=1`,
        {
          method: "GET",
          "Access-Control-Allow-Origin": "*",
        }
      );
      let processed = await res.json();
      setRequested(true);
      return processed.hits;
    } catch (err) {
      alert(err.message);
    }
  };

  const handleSubmitForm = async (e) => {
    e.preventDefault();
    setLoading(true);
    setImages([]);
    try {
      const imgs = await getImages(e.target[0].value);
      setImages(imgs);
    } catch (err) {
      alert(err.message);
    }
    setLoading(false);
  };

  const imagesHandler = () => {
    if (!images.length && requested) return <p>No results found</p>;
    else {
      return images.map((img, i) => {
        let { webformatURL: url, id } = img;
        return (
          <div className="img-container" key={id}>
            <img src={url} key={i} alt="" />
            {favorites.find((img) => img.id === id) ? (
              <div onClick={() => removeFromFavorites(url, id)}>
                <i className="fas fa-star favs filled" />
              </div>
            ) : (
              <div onClick={() => addToFavorites(url, id)}>
                <i className="far fa-star favs empty" />
              </div>
            )}
          </div>
        );
      });
    }
  };
  return (
    <div className="App">
      <div>
        <form id="form" onSubmit={handleSubmitForm}>
          <label htmlFor="searchTerm">Search an image</label>
          <input
            className="u-full-width"
            type="text"
            id="searchTerm"
            name="searchTerm"
          />
          <button type="submit">Search</button>
        </form>
      </div>
      {loading && (
        <div id="loading-image">
          <img className="loader" src={loader} alt="loader" />
        </div>
      )}
      <section class="images" id="section-images">
        {!loading && imagesHandler()}
      </section>
    </div>
  );
}
