// angular/src/app/home/home.component.ts
import { Component } from "@angular/core";
import { GetimagesService } from "../get-images.service";
import { GlobalVariables } from "../global-variables";
import {_Image, _Favorite} from "../types/Interfaces"

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"],
})

export class HomeComponent {

  searchTerm: string = "";
  loading: boolean = false;
  images: _Image[] = [];
  formSubmitted: boolean = false;

  constructor(private GetimagesService: GetimagesService) {}

  addToFavorites({ webformatURL: url, id }: _Favorite) : void {
    GlobalVariables.favorites.push({ url, id });
  }
  removeFromFavorites({ webformatURL: url, id }: _Favorite) : void{
    GlobalVariables.favorites.splice(
      GlobalVariables.favorites.indexOf({ url, id }),
      1
    );
  }
  isFavorite({ id }) : boolean {
    return GlobalVariables.favorites.find((img) => img.id === id) ? true : false;
  }

  toggleLoading() : void {
    this.loading = !this.loading;
  }
  handleFormSubmit() : void {
    this.images = [];
    this.toggleLoading();
    this.formSubmitted = true;
    this.GetimagesService.getImages(this.searchTerm).subscribe((res) => {
      this.images = res.hits;
      this.toggleLoading();
    });
  }
}

<form id="form" (ngSubmit)="handleFormSubmit()">
  <label for="searchTerm">Search an image</label>
  <input [(ngModel)]="searchTerm" class="u-full-width" type="text" id="searchTerm" name="searchTerm">
  <button type="submit" class="center-el">Search</button>
</form>
<img *ngIf="loading" class="loader" src="../../assets/loading.svg" alt="loading" />
<section *ngIf="images.length > 0 && !loading; else NoResult" class="images" id="section-images">
  <div *ngFor="let img of images" class="img-container">
    <img [src]="img.webformatURL" [alt]="searchTerm" />
    <i *ngIf="isFavorite(img); else NotFavorite" (click)="removeFromFavorites(img)" class="fas fa-star favs filled"></i>
    <ng-template #NotFavorite>
      <i (click)="addToFavorites(img)" class="far fa-star favs empty"></i>
    </ng-template>
  </div>
</section>
<ng-template #NoResult>
  <p *ngIf="formSubmitted && !loading">No images found</p>
</ng-template>

// react-js/src/pages/Home.js
import React, { useState } from "react";
import loader from "../loader.svg";
import "../App.css";

export default function Home(props) {
  const [loading, setLoading] = useState(false);
  const [images, setImages] = useState([]);
  const [requested, setRequested] = useState(false);
  let { favorites, addToFavorites, removeFromFavorites } = props;

  const getImages = async (searchTerm) => {
    try {
      setRequested(false);
      let res = await fetch(
        `https://pixabay.com/api/?key=16470380-d4d16b7e542ef904b93d0542c&q=${searchTerm}&image_type=photo&page=1`,
        {
          method: "GET",
          "Access-Control-Allow-Origin": "*",
        }
      );
      let processed = await res.json();
      setRequested(true);
      return processed.hits;
    } catch (err) {
      alert(err.message);
    }
  };

  const handleSubmitForm = async (e) => {
    e.preventDefault();
    setLoading(true);
    setImages([]);
    try {
      const imgs = await getImages(e.target[0].value);
      setImages(imgs);
    } catch (err) {
      alert(err.message);
    }
    setLoading(false);
  };

  const imagesHandler = () => {
    if (!images.length && requested) return <p>No results found</p>;
    else {
      return images.map((img, i) => {
        let { webformatURL: url, id } = img;
        return (
          <div className="img-container" key={id}>
            <img src={url} key={i} alt="" />
            {favorites.find((img) => img.id === id) ? (
              <div onClick={() => removeFromFavorites(url, id)}>
                <i className="fas fa-star favs filled" />
              </div>
            ) : (
              <div onClick={() => addToFavorites(url, id)}>
                <i className="far fa-star favs empty" />
              </div>
            )}
          </div>
        );
      });
    }
  };
  return (
    <div className="App">
      <div>
        <form id="form" onSubmit={handleSubmitForm}>
          <label htmlFor="searchTerm">Search an image</label>
          <input
            className="u-full-width"
            type="text"
            id="searchTerm"
            name="searchTerm"
          />
          <button type="submit">Search</button>
        </form>
      </div>
      {loading && (
        <div id="loading-image">
          <img className="loader" src={loader} alt="loader" />
        </div>
      )}
      <section class="images" id="section-images">
        {!loading && imagesHandler()}
      </section>
    </div>
  );
}
