// svelte/src/App.svelte
<script>
  import { Router, Link, Route } from "svelte-routing";
  import Home from "./Routes/Home.svelte";
  import Favorites from "./Routes/Favorites.svelte";

  export let url = "";
</script>

<Router {url}>
  <div>
    <Route path="/favorites">
      <nav>
        <Link to="/">Home</Link>
        /
        <span>Favorites</span>
      </nav>
      <h1 class="center-text">Favorites</h1>
      <Favorites />
    </Route>
    <Route path="/">
      <nav>
        <span>Home</span>
        /
        <Link to="/favorites">Favorites</Link>
      </nav>
      <!-- <h1 class="center-text">Svelte</h1> -->
	  <img class="logo" src="images/logo.png" alt="logo"/>
      <Home />
    </Route>
  </div>
</Router>

// vue3-composition-api/src/App.vue
<template>
  <div id="app">
    <div id="nav" v-if="$route.name == 'home'">
      <span>Home</span> /
      <router-link to="/favorites">Favorites</router-link>
    </div>
    <div id="nav" v-else>
      <router-link to="/">Home</router-link> /
      <span>Favorites</span>
    </div>
	<img v-if="$route.name == 'home'" class="logo" src="./assets/logo.png" alt="logo"/>
    <h1 v-else class="center-text">Favorites</h1>
    <router-view />
  </div>
</template>

<style>
@import "./assets/App.css";
</style>
