// vue3-composition-api/src/App.vue
<template>
  <div id="app">
    <div id="nav" v-if="$route.name == 'home'">
      <span>Home</span> /
      <router-link to="/favorites">Favorites</router-link>
    </div>
    <div id="nav" v-else>
      <router-link to="/">Home</router-link> /
      <span>Favorites</span>
    </div>
	<img v-if="$route.name == 'home'" class="logo" src="./assets/logo.png" alt="logo"/>
    <h1 v-else class="center-text">Favorites</h1>
    <router-view />
  </div>
</template>

<style>
@import "./assets/App.css";
</style>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(private router: Router) { }
	getCurrentRoute(){
		return this.router.url;
	}
}

<nav>
  <span *ngIf="getCurrentRoute() == '/'; else Home">Home</span>
  <ng-template #Home>
    <a routerLink="/" routerLinkActive="active">Home</a>
  </ng-template>
  /
  <span *ngIf="getCurrentRoute() == '/favorites'; else Fav">Favorites</span>
  <ng-template #Fav>
    <a routerLink="/favorites" routerLinkActive="active">Favorites</a>
  </ng-template>
</nav>
<img *ngIf="getCurrentRoute() == '/'; else Title" class="logo" src="../assets/logo.png" alt="logo" />
<ng-template #Title>
  <h1 class="center-text">Favorites</h1>
</ng-template>
<router-outlet></router-outlet>
